name: Book review

on:
  push:
    branches: [ main, review ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Chapter01-exercises:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: "Test examples and exercises"

    steps:
    - name: 'üìÇ Repository checkout'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive

    - name: 'üì¶ Install cc65 (complete cross development package for 65(C)02 systems)'
      run: |
        sudo apt update
        sudo apt install cc65

    - name: 'üì¶ Install Soft 65C02 (simulator, unit tester)'
      run: |
        git clone https://github.com/chanmix51/soft65c02.git
        cd soft65c02
        git checkout 76ab337 # known to work hash from 30 Jan 2026
        cargo build --workspace --release
        cargo install --path soft65c02_tester
        cargo install --path soft65c02_unit

    - name: 'üì¶ Install OSS CAD Suite'
      run: |
        curl -L -O https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2026-02-12/oss-cad-suite-linux-x64-20260212.tgz
        tar -xzf oss-cad-suite-linux-x64-*.tgz

    - name: 'üì¶ Install ARM cross compiler and Qemu'
      run: |
        sudo apt install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        sudo apt install qemu-system-arm qemu-user qemu-user-static

    - name: 'üîç Check tools'
      run: |
        . $GITHUB_WORKSPACE/oss-cad-suite/environment
        cc65 --version
        soft65c02_unit --version
        ghdl --version
        yosys --version

    - name: '‚öôÔ∏è Chapter 01: Run exercises 1~3, Babbage‚Äôs Analytical Engine addition/subtraction (examples in Python)'
      working-directory: 'Chapter01/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 Ex__1_test_single_digit_adder.py
        python3 Ex__2_test_40_digit_adder.py
        python3 Ex__3_test_single_digit_subtractor.py
        python3 Ex__3_test_40_digit_subtractor.py

    - name: '‚öôÔ∏è Chapter 01: Run 6502 ASM tests on examples and exercises'
      working-directory: 'Chapter01/soft65c02_unit_testing'
      continue-on-error: false
      run: |
        soft65c02_unit -v -i add-with-carry.yaml                   -b add-with-carry
        soft65c02_unit -v -i add-with-no-carry.yaml                -b add-with-no-carry
        soft65c02_unit -v -i add-with-signed-overflow.yaml         -b add-with-signed-overflow
        soft65c02_unit -v -i add-with-unsigned-overflow.yaml       -b add-with-unsigned-overflow
        soft65c02_unit -v -i subtract-with-borrow.yaml             -b subtract-with-borrow
        soft65c02_unit -v -i subtract-with-no-borrow.yaml          -b subtract-with-no-borrow
        soft65c02_unit -v -i subtract-with-signed-underflow.yaml   -b subtract-with-signed-underflow
        soft65c02_unit -v -i subtract-with-unsigned-underflow.yaml -b subtract-with-unsigned-underflow
        soft65c02_unit -v -i Ex__4_16_bit_addition.yaml            -b Ex__4_16_bit_addition
        soft65c02_unit -v -i Ex__5_16_bit_subtraction.yaml         -b Ex__5_16_bit_subtraction
        soft65c02_unit -v -i Ex__6_32_bit_addition.yaml            -b Ex__6_32_bit_addition

    - name: '‚öôÔ∏è Chapter 02: Run VHDL testbenches using GHDL'
      working-directory: 'Chapter02/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        . $GITHUB_WORKSPACE/oss-cad-suite/environment
        ./Ex__5_adder4_testbench.sh
        ./Ex__6_adder4_fulltestbench.sh

    - name: '‚öôÔ∏è Chapter 03: Run VHDL testbenches using GHDL'
      working-directory: 'Chapter03/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        . $GITHUB_WORKSPACE/oss-cad-suite/environment
        ./Ex__3_vhdl_overflow.sh

    - name: '‚öôÔ∏è Chapter 03: Run 6502 ASM tests on examples and exercises'
      working-directory: 'Chapter03/soft65c02_unit_testing'
      continue-on-error: false
      run: |
        soft65c02_unit -v -i absolute_addressing_mode.yaml            -b absolute_addressing_mode
        soft65c02_unit -v -i absolute_indexed_addressing_mode.yaml    -b absolute_indexed_addressing_mode
        soft65c02_unit -v -i immediate_addressing_mode.yaml           -b immediate_addressing_mode
        soft65c02_unit -v -i indirect_indexed_addressing_mode.yaml    -b indirect_indexed_addressing_mode
        soft65c02_unit -v -i looping_absolute_indexed_addressing.yaml -b looping_absolute_indexed_addressing
        soft65c02_unit -v -i Ex__4_checksum_alg.yaml                  -b Ex__4_checksum_alg
        soft65c02_unit -v -i Ex__5_checksum_subroutine.yaml           -b Ex__5_checksum_subroutine
        soft65c02_unit -v -i Ex__6_checksum_tests.yaml                -b Ex__6_checksum_tests

    - name: '‚öôÔ∏è Chapter 06: Run exercise 2, DCT formula (example in Python)'
      working-directory: 'Chapter06/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 Ex__2_dct_formula.py

    - name: '‚öôÔ∏è Chapter 07: Run exercise 3, column major order (example in Python)'
      working-directory: 'Chapter07/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 Ex__3_row_column_major_order.py

    - name: '‚öôÔ∏è Chapter 09: Chapter Files (example in C++)'
      working-directory: 'Chapter09/Chapter Files'
      continue-on-error: true
      run: |
        g++ integer_division.cpp -o integer_division
        ./integer_division

    - name: '‚öôÔ∏è Chapter 09: Answers to Exercises (examples in C++)'
      working-directory: 'Chapter09/Answers to Exercises/Code Files'
      continue-on-error: true
      run: |
        g++ Ex__1_float_format.cpp -o float_format
        ./float_format
        g++ Ex__2_double_format.cpp -o double_format
        ./double_format

    - name: '‚öôÔ∏è Chapter 10: Run exercise 3, neuron activation function (example in Python)'
      working-directory: 'Chapter10/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 Ex__3_activation_func.py

    - name: '‚öôÔ∏è Chapter 11: Chapter Files (examples in ARM assembly)'
      working-directory: 'Chapter11/Chapter Files'
      continue-on-error: true
      run: |
        arm-linux-gnueabihf-as -al=hello_arm.lst -o hello_arm.o hello_arm.S
        arm-linux-gnueabihf-ld -o hello_arm hello_arm.o
        cat hello_arm.lst
        qemu-arm -L /usr/arm-linux-gnueabihf/ hello_arm

    - name: '‚öôÔ∏è Chapter 11: Chapter Files (examples in ARM64 assembly)'
      working-directory: 'Chapter11/Chapter Files'
      continue-on-error: true
      run: |
        aarch64-linux-gnu-as -al=hello_arm64.lst -o hello_arm64.o hello_arm64.S
        aarch64-linux-gnu-ld -o hello_arm64 hello_arm64.o
        cat hello_arm64.lst
        qemu-aarch64 -L /usr/aarch64-linux-gnu/ hello_arm64

    - name: '‚öôÔ∏è Chapter 11: Answers to Exercises, Exercise 5 (examples in ARM assembly)'
      working-directory: 'Chapter11/Answers to Exercises/Code Files'
      continue-on-error: true
      run: |
        arm-linux-gnueabihf-as -al=Ex__5_hello_arm.lst -o Ex__5_hello_arm.o Ex__5_hello_arm.S
        arm-linux-gnueabihf-ld -o Ex__5_hello_arm Ex__5_hello_arm.o
        qemu-arm -L /usr/arm-linux-gnueabihf/ Ex__5_hello_arm
        cat Ex__5_hello_arm.lst

    - name: '‚öôÔ∏è Chapter 11: Answers to Exercises, Exercise 6 (examples in ARM assembly)'
      working-directory: 'Chapter11/Answers to Exercises/Code Files'
      continue-on-error: true
      run: |
        arm-linux-gnueabihf-as -al=Ex__6_expr_arm.lst -o Ex__6_expr_arm.o Ex__6_expr_arm.S
        arm-linux-gnueabihf-ld -o Ex__6_expr_arm Ex__6_expr_arm.o
        qemu-arm -L /usr/arm-linux-gnueabihf/ Ex__6_expr_arm
        cat Ex__6_expr_arm.lst

    - name: '‚öôÔ∏è Chapter 11: Answers to Exercises, Exercise 7 (examples in ARM64 assembly)'
      working-directory: 'Chapter11/Answers to Exercises/Code Files'
      continue-on-error: true
      run: |
        aarch64-linux-android-as -al=Ex__7_hello_arm64.lst -o Ex__7_hello_arm64.o Ex__7_hello_arm64.S
        aarch64-linux-android-ld -o Ex__7_hello_arm64 Ex__7_hello_arm64.o
        qemu-aarch64 -L /usr/aarch64-linux-gnu/ Ex__7_hello_arm64
        cat Ex__7_hello_arm64.lst

    - name: '‚öôÔ∏è Chapter 11: Answers to Exercises, Exercise 8 (examples in ARM64 assembly)'
      working-directory: 'Chapter11/Answers to Exercises/Code Files'
      continue-on-error: true
      run: |
        aarch64-linux-android-as -al=Ex__8_expr_arm64.lst -o Ex__8_expr_arm64.o Ex__8_expr_arm64.S
        aarch64-linux-android-ld -o Ex__8_expr_arm64 Ex__8_expr_arm64.o
        qemu-aarch64 -L /usr/aarch64-linux-gnu/ Ex__8_expr_arm64
        cat Ex__8_expr_arm64.lst

    - name: '‚öôÔ∏è Chapter 17: Run exercise 1, compute block hash (example in Python)'
      working-directory: 'Chapter17/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 Ex__1_compute_block_hash.py

    - name: '‚öôÔ∏è Chapter 18: Run exercise 1/2/3 (examples in Python)'
      working-directory: 'Chapter18/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 -m venv chapter18
        source chapter18/bin/activate
        pip3 install tensorflow
        pip3 install matplotlib
        python3 Ex__2_load_dataset.py
        python3 Ex__3_create_network.py
        python3 Ex__4_train_model.py

    - name: '‚öôÔ∏è Chapter 19: Run exercise 3/4 (examples in Python)'
      working-directory: 'Chapter19/Answers to Exercises/Code Files'
      continue-on-error: false
      run: |
        python3 Ex__3_ghz_sim.py
        python3 Ex__4_ghz_sim.py
