name: Book review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Chapter01-exercises:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: "Test examples and exercises"

    steps:
    - name: 'üìÇ Repository checkout'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '‚öôÔ∏è Run exercises 1~3, Babbage‚Äôs Analytical Engine addition/subtraction (examples in Python)'
      working-directory: 'Chapter01/Answers to Exercises/src'
      continue-on-error: true
      run: |
        python3 Ex__1_test_single_digit_adder.py
        python3 Ex__2_test_40_digit_adder.py
        python3 Ex__3_test_single_digit_subtractor.py
        python3 Ex__3_test_40_digit_subtractor.py
